/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as CheckInsRouteImport } from './routes/check-ins'
import { Route as PracticesRouteImport } from './routes/practices'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as DoctorPatientsIndexRouteImport } from './routes/doctor/patients/index'
import { Route as DoctorPatientsPatientIdRouteImport } from './routes/doctor/patients/$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInsRoute = CheckInsRouteImport.update({
  id: '/check-ins',
  path: '/check-ins',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticesRoute = PracticesRouteImport.update({
  id: '/practices',
  path: '/practices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsIndexRoute = DoctorPatientsIndexRouteImport.update({
  id: '/doctor/patients/',
  path: '/doctor/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsPatientIdRoute = DoctorPatientsPatientIdRouteImport.update({
  id: '/doctor/patients/$patientId',
  path: '/doctor/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/check-ins': typeof CheckInsRoute
  '/practices': typeof PracticesRoute
  '/profile': typeof ProfileRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/check-ins': typeof CheckInsRoute
  '/practices': typeof PracticesRoute
  '/profile': typeof ProfileRoute
  '/doctor': typeof DoctorIndexRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdRoute
  '/doctor/patients': typeof DoctorPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/check-ins': typeof CheckInsRoute
  '/practices': typeof PracticesRoute
  '/profile': typeof ProfileRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/check-ins'
    | '/practices'
    | '/profile'
    | '/doctor/'
    | '/doctor/patients/$patientId'
    | '/doctor/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/check-ins'
    | '/practices'
    | '/profile'
    | '/doctor'
    | '/doctor/patients/$patientId'
    | '/doctor/patients'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/check-ins'
    | '/practices'
    | '/profile'
    | '/doctor/'
    | '/doctor/patients/$patientId'
    | '/doctor/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  CheckInsRoute: typeof CheckInsRoute
  PracticesRoute: typeof PracticesRoute
  ProfileRoute: typeof ProfileRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorPatientsPatientIdRoute: typeof DoctorPatientsPatientIdRoute
  DoctorPatientsIndexRoute: typeof DoctorPatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-ins': {
      id: '/check-ins'
      path: '/check-ins'
      fullPath: '/check-ins'
      preLoaderRoute: typeof CheckInsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practices': {
      id: '/practices'
      path: '/practices'
      fullPath: '/practices'
      preLoaderRoute: typeof PracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients/': {
      id: '/doctor/patients/'
      path: '/doctor/patients'
      fullPath: '/doctor/patients/'
      preLoaderRoute: typeof DoctorPatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients/$patientId': {
      id: '/doctor/patients/$patientId'
      path: '/doctor/patients/$patientId'
      fullPath: '/doctor/patients/$patientId'
      preLoaderRoute: typeof DoctorPatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  CheckInsRoute: CheckInsRoute,
  PracticesRoute: PracticesRoute,
  ProfileRoute: ProfileRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorPatientsPatientIdRoute: DoctorPatientsPatientIdRoute,
  DoctorPatientsIndexRoute: DoctorPatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
